name: Build Android APK

on:
  workflow_dispatch: 

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Install npm dependencies
        run: npm install

      - name: Create Web Dir & Config
        run: |
          mkdir -p www
          echo "<html><body>Capacitor Web View</body></html>" > www/index.html

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build Android APK and AAB
        run: |
          cd android
          sed -i 's/\r$//' gradlew
          chmod +x ./gradlew
          ./gradlew assembleDebug
          ./gradlew bundleRelease

      - name: Generate Keystore & Sign AAB
        run: |
          if [ ! -f "android/app/zomee-key.jks" ]; then
            echo "Keystore not found! Generating a new one..."
            keytool -genkey -v -keystore android/app/zomee-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias zomee -dname "CN=Zomee, OU=Zomee, O=Zomee, L=Dubai, S=Dubai, C=AE" -storepass "zomee12345" -keypass "zomee12345"
          else
            echo "Keystore found! Using existing keystore..."
          fi
          
          # Sign the AAB file
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore android/app/zomee-key.jks -storepass "zomee12345" -keypass "zomee12345" android/app/build/outputs/bundle/release/app-release.aab zomee

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload SIGNED AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-SIGNED.aab
          path: android/app/build/outputs/bundle/release/app-release.aab

      - name: Upload Keystore (CRITICAL - KEEP SAFE)
        uses: actions/upload-artifact@v4
        with:
          name: YOUR-KEYSTORE-FILE.jks
          path: android/app/zomee-key.jks
